In [11]:
import numpy as np

# 1. Create a 3x3x3 array with random values 

In [23]:
arr1 = np.random.rand(3, 3, 3)
print(arr1)

[[[0.41999805 0.36052152 0.08705155]
  [0.24529272 0.2541436  0.42785775]
  [0.64508858 0.26412175 0.08956575]]

 [[0.67113869 0.20422648 0.63901676]
  [0.71937719 0.32789868 0.16534628]
  [0.05496171 0.96923157 0.92549015]]

 [[0.43326922 0.54417395 0.306884  ]
  [0.27641081 0.71797527 0.37624746]
  [0.71150475 0.24729561 0.76412909]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [13]:
arr2 = np.zeros([5, 5])
arr2[1, 0] = 1
arr2[2, 1] = 2
arr2[3, 2] = 3
arr2[4, 3] = 4
print(arr2)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [123]:
arr3 = np.full([8, 8], 0)

for i in range(8):
  for j in range(8):
    if((i+j)%2==0):
      arr3[i, j] = 1

print(arr3)

[[1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]]


# 4. Normalize a 5x5 random matrix

In [78]:
arr4 = np.random.randint(0,100, size=[5, 5])
norm = arr4/(100)
print(norm)

[[0.18 0.14 0.82 0.98 0.23]
 [0.69 0.11 0.57 0.26 0.24]
 [0.36 0.59 0.89 0.67 0.01]
 [0.52 0.39 0.3  0.13 0.71]
 [0.26 0.75 0.81 0.42 0.06]]


# 5.  How to find common values between two arrays?

In [37]:
a1 = np.array([1, 3, 4, 4, 5, 7, 9])
a2 = np.array([4, 6, 3, 9, 5, 7, 8])

print(np.intersect1d(a1, a2))

[3 4 5 7 9]


# 6.How to get the dates of yesterday, today and tomorrow?

In [128]:
import datetime

today = int(datetime.datetime.now().strftime("%d"))

yesterday = today - 1
tomorrow = today + 1

print("Yesterday: ", yesterday)
print("Today: ", today)
print("Tomorrow: ", tomorrow)

Yesterday:  24
Today:  25
Tomorrow:  26


# 7. Consider two random array A and B, check if they are equal

In [39]:
A = np.array([1, 2, 3, 4, 8])

B = np.array([1, 2, 3, 4, 8])

list(A) == list(B)

True

# 8.Create random vector of size 10 and replace the maximum value by 0 

In [48]:
rand_array = np.random.rand(10)

print(rand_array)
rand_array = np.where(rand_array==rand_array.max(), 0, rand_array) 
print(rand_array)

[0.82266743 0.56843506 0.63298073 0.59119472 0.21796074 0.67516005
 0.08511834 0.96576513 0.84487678 0.15082212]
[0.82266743 0.56843506 0.63298073 0.59119472 0.21796074 0.67516005
 0.08511834 0.         0.84487678 0.15082212]


# 9. How to print all the values of an array?

In [51]:
array = np.array([[1, 2, 3, 4, 5], 
         [6, 7, 8, 9, 10]])
print(array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


# 10.Subtract the mean of each row of a matrix

In [113]:
arr10 = np.array([[1, 2, 3], 
                  [5, 6, 7], 
                  [8, 9, 10]])

arr10[0] -= int(arr10.mean(1)[0])
arr10[1] -= int(arr10.mean(1)[1])
arr10[2] -= int(arr10.mean(1)[2])

print(arr10)

[[-1  0  1]
 [-1  0  1]
 [-1  0  1]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [83]:
v = np.array([2, 3, 5])
v += 1
print(v)

[3 4 6]


# 12.How to get the diagonal of a dot product?

In [90]:
arr12_1 = np.array([[1, 2, 3], 
                    [5, 6, 7], 
                    [8, 9, 10]])
arr12_2 = np.array([[10, 11, 12], 
                    [20, 21, 22], 
                    [30, 31, 32]])

dot = np.dot(arr12_1, arr12_2)

diag = dot.diagonal()

print(diag)

[140 398 614]


# 13.How to find the most frequent value in an array?

In [67]:
arr13 = np.array([3, 24, 24, 34, 214, 3, 214, 24, 214, 0.452, 2, 4])

# 14.How to get the n largest values of an array

In [94]:
import pandas as pd

arr14 = np.array([3, 24, 24, 34, 214, 3, 213, 132, 24, 0.452])

data = pd.Series(arr14)

print(data.mode()[0])

24.0


# 15.How to create a record array from a regular array?

In [99]:
arr15 = np.array([[1, 2, 3], 
                  [5, 6, 7], 
                  [8, 9, 10]])

rec_array = np.rec.array(arr15)
print(rec_array)

[[ 1  2  3]
 [ 5  6  7]
 [ 8  9 10]]
